DjangoApp/eazytapa/eazytapa/urls.py
from django.contrib import admin
from django.urls import path

import web.views as wv

urlpatterns = [
    path('', wv.home, name='Home'),
    path('bar/<int:bar_id>/', wv.bar, name = 'Bar'),
    path('tapa/<int:pk>', wv.TapaView.as_view(), name = 'Tapa'),
    path('admin/', admin.site.urls),
]

DjangoApp/eazytapa/web/models.py
from django.db import models

# Create your models here.


class Bar(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self) -> str:
        return self.name



class Tapa(models.Model):
    name = models.CharField(max_length=256)
    bar = models.ForeignKey(Bar, on_delete=models.CASCADE)

    def __str__(self) -> str:
            return self.name+"@"+self.bar.name

DjangoApp/eazytapa/web/views.py
from django.shortcuts import render
from django.http import HttpResponse
from web.models import Bar, Tapa
from django.views import generic

# Create your views here.

# def home(request):
#     bars = Bar.objects.all()[:5]
#     dades = {
#         'bars': bars,
#     }
#     resposta = [bar.name for bar in bars]
#     return HttpResponse("<br/>".join(resposta))

def home(request):
    bars = Bar.objects.all()[:5]
    return render(request, "web/index.html", {"bars": bars})


def bar(request, bar_id):
    try:
        bar = Bar.objects.get(pk=bar_id)
    except Bar.DoesNotExist:
        raise Http404("Aquest Bar no existeix")
    return render(request, 'web/bar.html', {'bar': bar})

class TapaView(generic.DetailView):
    model = Tapa
    template_name = 'web/tapa.html'

DjangoApp/eazytapa/web/templates/web/bar.html
{{ bar }}

<br />
<ul>
    {% for tapa in bar.tapa_set.all %}
    <li><a href={% url 'Tapa' tapa.id %}>{{ tapa.name }}</a></li>
    {% endfor %}
</ul>

DjangoApp/eazytapa/web/templates/web/index.html
On anar de tapes avui?
<ul>
    {% for bar in bars %}
    <li><a href={% url 'Bar' bar.id %}>{{ bar.name }}</a></li>
    {% endfor %}
</ul>

DjangoApp/eazytapa/web/templates/web/tapa.html
{{ tapa.name }}

<br /><a href={% url 'Home' %}>Home</a>